CREATE TABLE SELLER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE BUYER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE BOOK (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    AUTHOR VARCHAR(255) NOT NULL,
    PRICE DOUBLE NOT NULL,
    SELLER_ID BIGINT,
    FOREIGN KEY (SELLER_ID) REFERENCES SELLER(ID)
);
